# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 2, 4, 22, 3, 17, 259792)),
        ),
    ]
