# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20170204_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 2, 7, 19, 18, 9, 810899, tzinfo=utc)),
        ),
    ]
