# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_auto_20170208_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
